const fs = require('fs');
const c = fs.readFileSync('index.html', 'utf8');
const start = c.indexOf('<div id="start-screen"');
const afterStart = c.substring(start);
const firstClose = afterStart.indexOf('</div>');
const secondClose = afterStart.indexOf('</div>', firstClose + 1);
const thirdClose = afterStart.indexOf('</div>', secondClose + 1);
const fourthClose = afterStart.indexOf('</div>', thirdClose + 1);
const fifthClose = afterStart.indexOf('</div>', fourthClose + 1);
const sixthClose = afterStart.indexOf('</div>', fifthClose + 1);
console.log('fifth:', fifthClose);
console.log('sixth:', sixthClose);
console.log('context fifth:', afterStart.substring(fifthClose, fifthClose + 50));
console.log('sixth context:', afterStart.substring(sixthClose, sixthClose + 50));
console.log('end pos in full:', start + 500 + sixthClose + 6);